# Generated by Django 5.2.6 on 2025-09-21 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpreference',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='community.blog'),
        ),
        migrations.AddField(
            model_name='visitorpreference',
            name='liked_projects',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='community.project'),
        ),
        migrations.AddField(
            model_name='visitorpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
