# Generated by Django 5.2.6 on 2025-09-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_visitorpreference_liked_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activity_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leaderboard_rank',
        ),
    ]
