# Generated by Django 5.2.5 on 2025-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_activity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_score',
            field=models.PositiveIntegerField(default=0, help_text='Total activity points earned'),
        ),
    ]
